# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
# Required by RNFirebase
pod 'Firebase/Core', '~> 5.15.0'
pod 'Firebase/Auth', '~> 5.15.0'

target 'ELORankings' do

  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ELORankings


  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'ELORankingsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ELORankings-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ELORankings-tvOS

  target 'ELORankings-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
